// This file is auto-generated by @hey-api/openapi-ts

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  /**
   * Message
   */
  message: string;
  /**
   * Status
   */
  status?: string;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
  /**
   * Message
   */
  message: string;
  /**
   * Status
   */
  status?: string;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type RootGetError = RootGetErrors[keyof RootGetErrors];

export interface RootGetResponses {
  /**
   * Successful response
   */
  200: SuccessResponse;
}

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:9000" | (string & {});
};
